name: C/C++ CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: checking cmake version
        run: cmake --version

      - name: installing c++/c compiler
        run: sudo apt install build-essential

      - name: checking complier version
        run: g++ --version

      - name: installing git
        run: sudo apt install git

      - name: checking git version
        run: git --version

      - name: building our project
        run: make build-project

      - name: checking build directory
        run: ls -l build

      - name: running tests
        run: make run-all-tests

